import {
  LayoutDashboard,
  Users,
  Inbox,
  Building2,
  CalendarDays,
  CalendarCheck,
  ClipboardList,
  Receipt,
  DollarSign,
  BarChart3,
  ShieldCheck,
  ScrollText,
  Plug,
  ArrowDownToLine,
  Phone,
  Send,
  Sprout,
  Handshake,
  Workflow,
  Mail,
  Bot,
  type LucideIcon,
} from 'lucide-react';

/** Icon lookup for NavItem.icon names, shared by the sidebar and mobile nav. */
export const NAV_ICONS: Record<string, LucideIcon> = {
  Bot,
  LayoutDashboard,
  Users,
  Inbox,
  Building2,
  CalendarDays,
  CalendarCheck,
  ClipboardList,
  Receipt,
  DollarSign,
  BarChart3,
  ShieldCheck,
  ScrollText,
  Plug,
  ArrowDownToLine,
  Phone,
  Send,
  Sprout,
  Handshake,
  Workflow,
  Mail,
};
